/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import PatientPackage.Patient;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import static ui.RegistrationJFrame.patDr;

/**
 *
 * @author Rohit Paul G
 */
public class AdminWorkAreaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminWorkAreaJFrame
     */
    public AdminWorkAreaJFrame() {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        AdminToolBar = new javax.swing.JPanel();
        btnDoctorLogOut = new javax.swing.JButton();
        AdminWorkArea = new javax.swing.JPanel();
        AdminWork = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnManagePatients = new javax.swing.JButton();
        btnManageDoctors = new javax.swing.JButton();
        btnManageHospitals = new javax.swing.JButton();
        ManagePatientsArea = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientRecordControl = new javax.swing.JTable();
        btnViewPatientRecord = new javax.swing.JButton();
        btnUpdatePatientRecord = new javax.swing.JButton();
        btnDeactivatePatientRecord = new javax.swing.JButton();
        btnBackToAdminWork = new javax.swing.JButton();
        ManageDoctorsArea = new javax.swing.JPanel();
        ManageHospitalsArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        AdminToolBar.setBackground(new java.awt.Color(205, 209, 228));

        btnDoctorLogOut.setText("Log Out");
        btnDoctorLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminToolBarLayout = new javax.swing.GroupLayout(AdminToolBar);
        AdminToolBar.setLayout(AdminToolBarLayout);
        AdminToolBarLayout.setHorizontalGroup(
            AdminToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDoctorLogOut)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        AdminToolBarLayout.setVerticalGroup(
            AdminToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminToolBarLayout.createSequentialGroup()
                .addContainerGap(626, Short.MAX_VALUE)
                .addComponent(btnDoctorLogOut)
                .addGap(97, 97, 97))
        );

        jSplitPane1.setLeftComponent(AdminToolBar);

        AdminWorkArea.setLayout(new java.awt.CardLayout());

        AdminWork.setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("~ Hello Admin ~");

        btnManagePatients.setText("Manage Patients");
        btnManagePatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManagePatientsMouseClicked(evt);
            }
        });
        btnManagePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientsActionPerformed(evt);
            }
        });

        btnManageDoctors.setText("Manage Doctors");
        btnManageDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDoctorsActionPerformed(evt);
            }
        });

        btnManageHospitals.setText("Manage Hospitals");

        javax.swing.GroupLayout AdminWorkLayout = new javax.swing.GroupLayout(AdminWork);
        AdminWork.setLayout(AdminWorkLayout);
        AdminWorkLayout.setHorizontalGroup(
            AdminWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminWorkLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnManagePatients)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnManageDoctors)
                .addGap(141, 141, 141))
            .addGroup(AdminWorkLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addGroup(AdminWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminWorkLayout.setVerticalGroup(
            AdminWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminWorkLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(154, 154, 154)
                .addGroup(AdminWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePatients)
                    .addComponent(btnManageDoctors))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnManageHospitals)
                .addGap(263, 263, 263))
        );

        AdminWorkArea.add(AdminWork, "card2");

        ManagePatientsArea.setBackground(new java.awt.Color(204, 255, 204));

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("~ Patient Record Control ~");

        tblPatientRecordControl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Age", "Date of Birth", "Height", "Weight", "Phone", "Hospital", "Role", "City", "Community", "House Address", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatientRecordControl);

        btnViewPatientRecord.setText("View Patient");

        btnUpdatePatientRecord.setText("Update Patient");

        btnDeactivatePatientRecord.setText("Deactivate Patient");

        btnBackToAdminWork.setText("<< Back to Home");

        javax.swing.GroupLayout ManagePatientsAreaLayout = new javax.swing.GroupLayout(ManagePatientsArea);
        ManagePatientsArea.setLayout(ManagePatientsAreaLayout);
        ManagePatientsAreaLayout.setHorizontalGroup(
            ManagePatientsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePatientsAreaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagePatientsAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(ManagePatientsAreaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnViewPatientRecord)
                .addGap(18, 18, 18)
                .addComponent(btnUpdatePatientRecord)
                .addGap(18, 18, 18)
                .addComponent(btnDeactivatePatientRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagePatientsAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToAdminWork)
                .addGap(14, 14, 14))
        );

        ManagePatientsAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeactivatePatientRecord, btnUpdatePatientRecord, btnViewPatientRecord});

        ManagePatientsAreaLayout.setVerticalGroup(
            ManagePatientsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePatientsAreaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ManagePatientsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewPatientRecord)
                    .addComponent(btnUpdatePatientRecord)
                    .addComponent(btnDeactivatePatientRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(btnBackToAdminWork)
                .addGap(17, 17, 17))
        );

        AdminWorkArea.add(ManagePatientsArea, "card3");

        ManageDoctorsArea.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout ManageDoctorsAreaLayout = new javax.swing.GroupLayout(ManageDoctorsArea);
        ManageDoctorsArea.setLayout(ManageDoctorsAreaLayout);
        ManageDoctorsAreaLayout.setHorizontalGroup(
            ManageDoctorsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        ManageDoctorsAreaLayout.setVerticalGroup(
            ManageDoctorsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );

        AdminWorkArea.add(ManageDoctorsArea, "card4");

        ManageHospitalsArea.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ManageHospitalsAreaLayout = new javax.swing.GroupLayout(ManageHospitalsArea);
        ManageHospitalsArea.setLayout(ManageHospitalsAreaLayout);
        ManageHospitalsAreaLayout.setHorizontalGroup(
            ManageHospitalsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        ManageHospitalsAreaLayout.setVerticalGroup(
            ManageHospitalsAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );

        AdminWorkArea.add(ManageHospitalsArea, "card5");

        jSplitPane1.setRightComponent(AdminWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorLogOutActionPerformed
        // TODO add your handling code here:
        LoginJFrame lgFrame = new LoginJFrame();
        lgFrame.setVisible(true);
        lgFrame.pack();
        lgFrame.setLocationRelativeTo(null);
        lgFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnDoctorLogOutActionPerformed

    private void btnManagePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagePatientsActionPerformed

    private void btnManageDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDoctorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageDoctorsActionPerformed

    private void btnManagePatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagePatientsMouseClicked
        // TODO add your handling code here:
        
        //DoctorWorkArea.removeAll();
        //DoctorWorkArea.add(ViewVitalsArea);
        //DoctorWorkArea.repaint();
        //DoctorWorkArea.revalidate();
        
        AdminWorkArea.removeAll();
        AdminWorkArea.add(ManagePatientsArea);
        AdminWorkArea.repaint();
        AdminWorkArea.revalidate();
    }//GEN-LAST:event_btnManagePatientsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWorkAreaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminToolBar;
    private javax.swing.JPanel AdminWork;
    private javax.swing.JPanel AdminWorkArea;
    private javax.swing.JPanel ManageDoctorsArea;
    private javax.swing.JPanel ManageHospitalsArea;
    private javax.swing.JPanel ManagePatientsArea;
    private javax.swing.JButton btnBackToAdminWork;
    private javax.swing.JButton btnDeactivatePatientRecord;
    private javax.swing.JButton btnDoctorLogOut;
    private javax.swing.JButton btnManageDoctors;
    private javax.swing.JButton btnManageHospitals;
    private javax.swing.JButton btnManagePatients;
    private javax.swing.JButton btnUpdatePatientRecord;
    private javax.swing.JButton btnViewPatientRecord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTable tblPatientRecordControl;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblPatientRecordControl.getModel();
        model.setRowCount(0);
        
        if (patDr.getPatientlist() != null){
            for (Patient pa : patDr.getPatientlist()){
                Object[] rowPat = new Object[14];
                
                rowPat[0] = pa.getfName();
                rowPat[1] = pa.getlName();
                rowPat[2] = pa.getAge();
                rowPat[3] = pa.getDateOfBirth();
                rowPat[4] = pa.getHeight();
                rowPat[5] = pa.getWeight();
                rowPat[6] = pa.getMobilePhn();
                rowPat[7] = pa.getHospital();
                rowPat[8] = pa.getRoles();
                rowPat[9] = pa.getCity();
                rowPat[10] = pa.getCommunity();
                rowPat[11] = pa.getHouseAddress();
                rowPat[12] = pa.getUserName();
                rowPat[13] = pa.getPassWord();
                
                model.addRow(rowPat);
                
            }
        }
    }
}
