/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import DoctorPackage.Doctor;
import DoctorPackage.DoctorDirectory;
import EncounterPackage.EncounterHistory;
import PatientPackage.Patient;
import PersonPackage.Person;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static ui.RegistrationJFrame.docDr;
import static ui.RegistrationJFrame.patDr;

/**
import java.awt.event.WindowEvent;
import static ui.RegistrationJFrame.docDr;
import static ui.RegistrationJFrame.patDr;
 *
 * @author Rohit Paul G
 */
public class LoginJFrame extends javax.swing.JFrame {
    public static Person per = new Person();
    public static Doctor doc = new Doctor(); 
    
    
    /**
     * Creates new form LoginJFrame
     */
    
    public LoginJFrame() {
        
        initComponents();
        this.setLocationRelativeTo(null); //shows the login page in the center of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblHideWindow = new javax.swing.JLabel();
        lblCloseWindow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnSignIn = new javax.swing.JButton();
        lblOr = new javax.swing.JLabel();
        lblRegistration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(205, 209, 228));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("~ Cristo es Dios General Hospital  ~");

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Sign In");

        lblHideWindow.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHideWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHideWindow.setText("-");
        lblHideWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHideWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHideWindowMouseClicked(evt);
            }
        });

        lblCloseWindow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCloseWindow.setForeground(new java.awt.Color(255, 51, 0));
        lblCloseWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseWindow.setText("X");
        lblCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseWindowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHideWindow)
                .addGap(18, 18, 18)
                .addComponent(lblCloseWindow)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHideWindow)
                    .addComponent(lblCloseWindow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle2)
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(228, 241, 254));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPassword.setText("Password:");

        btnSignIn.setBackground(new java.awt.Color(3, 201, 169));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        lblOr.setText("or");

        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setText("Click here to register");
        lblRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword)
                    .addComponent(lblUsername))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSignIn)
                        .addGap(18, 18, 18)
                        .addComponent(lblOr)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignIn)
                    .addComponent(lblOr))
                .addGap(27, 27, 27)
                .addComponent(lblRegistration)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblPassword, lblUsername});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseWindowMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseWindowMouseClicked

    private void lblHideWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideWindowMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblHideWindowMouseClicked

    private void lblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrationMouseClicked
        // TODO add your handling code here:
        RegistrationJFrame rgf = new RegistrationJFrame();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_lblRegistrationMouseClicked

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        //RegistrationJFrame.usernameANDpassword.con
        //String passWord = pwdPassword.getText();
        //String userName = txtUsername.getText();
        
        //if (passWord.equals(passWord) && doc.equals(passWord)){
          //  pwdPassword.setText(null);
        //}
        //else if (userName.equals(userName) && doc.equals(userName)){
          //  txtUsername.setText(null);
        //}
        
        //JOptionPane.showMessageDialog(this, "Entity login successful!");
        
        Person pdata = checkMyPerson();
        Doctor ddata = checkMyDoctor(); //Doctor ddata = checkMyDoctor();
        
        if (pdata!=null||ddata!=null){  //pdata!=null||ddata!=null
            if (pdata.getRoles() == "Patient"){
                //JOptionPane.showMessageDialog(this, "New entity 'Patient' logged in!");
                PatientWorkAreaJFrame patWorkArea = new PatientWorkAreaJFrame();
                patWorkArea.setVisible(true);
                patWorkArea.pack();
                patWorkArea.setLocationRelativeTo(null);
                patWorkArea.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                this.dispose();
            }
            else if (ddata.getRoles() == "Doctor"){
                //the below code to be changed to include for DoctorWorkAreaJFrame
               //PatientWorkAreaJFrame patWorkArea = new PatientWorkAreaJFrame();
                //patWorkArea.setVisible(true);
                //JOptionPane.showMessageDialog(this, "Doctor is logged in!");
                DoctorWorkAreaJFrame docWorkArea = new DoctorWorkAreaJFrame();
                docWorkArea.setVisible(true);
                docWorkArea.pack();
                docWorkArea.setLocationRelativeTo(null);
                docWorkArea.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                //patWorkArea.pack();
                //patWorkArea.setLocationRelativeTo(null);
                //patWorkArea.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            }
        }    
           
    }//GEN-LAST:event_btnSignInActionPerformed

    public  Person checkMyPerson(){
        Person per1 = new Person();
        for(Person p : patDr.getPatientlist()){
            if (p.getUserName().equals(txtUsername.getText()) && p.getPassWord().equals(String.valueOf(pwdPassword.getPassword()))){
                System.out.println(p.getUserName());
                per1 = p;
            }
        }
        return per1;
    }
    
    public Doctor checkMyDoctor(){  
        Doctor doc1 = new Doctor();
        for (Doctor d : docDr.getDoctorList()){  
            if (d.getUserName().equals(txtUsername.getText()) && d.getPassWord().equals(String.valueOf(pwdPassword.getPassword()))){
                System.out.println(d.getUserName());
                doc1 = d;
            }
        }
        return doc1;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCloseWindow;
    private javax.swing.JLabel lblHideWindow;
    private javax.swing.JLabel lblOr;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
