/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import DoctorPackage.Doctor;
import PatientPackage.Patient;
import PersonPackage.Person;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import static ui.LoginJFrame.per;

/**
 *
 * @author Rohit Paul G
 */
public class PatientWorkAreaJFrame extends javax.swing.JFrame {
    Person personToWorkWith = LoginJFrame.per;
    /**
     * Creates new form PatientWorkAreaJFrame
     */
    
    
    public PatientWorkAreaJFrame() {
        initComponents();
        populateTable();
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientWorkSpaceSplitPane = new javax.swing.JSplitPane();
        PatientToolBar = new javax.swing.JPanel();
        btnPatientLogOut = new javax.swing.JButton();
        PatientWorkArea = new javax.swing.JPanel();
        PatientWork = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientEncountersjTable = new javax.swing.JTable();
        btnCreateEncounter = new javax.swing.JButton();
        AddEncounter = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        lblPatientFName = new javax.swing.JLabel();
        lblPatientLName = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        lblPatientMobilePhn = new javax.swing.JLabel();
        lblPatientListOfDoctors = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPatientFName = new javax.swing.JTextField();
        txtPatientLName = new javax.swing.JTextField();
        txtPatientAge = new javax.swing.JTextField();
        txtPatientMobilePhn = new javax.swing.JTextField();
        txtPatientListOfDoctors = new javax.swing.JComboBox<>();
        lblPatientEncounterID = new javax.swing.JLabel();
        lblPatientEncounterTime = new javax.swing.JLabel();
        lblPatientBloodType = new javax.swing.JLabel();
        lblPatientAdmitDate = new javax.swing.JLabel();
        lblPatientSymptoms = new javax.swing.JLabel();
        txtPatientEncounterID = new javax.swing.JTextField();
        txtPatientEncounterTime = new javax.swing.JTextField();
        txtPatientBloodType = new javax.swing.JTextField();
        txtPatientAdmitDate = new javax.swing.JTextField();
        txtPatientSymptoms = new javax.swing.JTextField();
        btnSubmitEncounter = new javax.swing.JButton();
        btnBackToPatientMainPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);

        PatientToolBar.setBackground(new java.awt.Color(205, 209, 228));

        btnPatientLogOut.setText("Log Out");
        btnPatientLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientToolBarLayout = new javax.swing.GroupLayout(PatientToolBar);
        PatientToolBar.setLayout(PatientToolBarLayout);
        PatientToolBarLayout.setHorizontalGroup(
            PatientToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPatientLogOut)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        PatientToolBarLayout.setVerticalGroup(
            PatientToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientToolBarLayout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addComponent(btnPatientLogOut)
                .addGap(107, 107, 107))
        );

        PatientWorkSpaceSplitPane.setLeftComponent(PatientToolBar);

        PatientWorkArea.setLayout(new java.awt.CardLayout());

        PatientWork.setBackground(new java.awt.Color(228, 241, 254));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("~ Hello Patient ~");

        PatientEncountersjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PatientEncountersjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientEncountersjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PatientEncountersjTable);

        btnCreateEncounter.setText("Create Encounter");
        btnCreateEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEncounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientWorkLayout = new javax.swing.GroupLayout(PatientWork);
        PatientWork.setLayout(PatientWorkLayout);
        PatientWorkLayout.setHorizontalGroup(
            PatientWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PatientWorkLayout.createSequentialGroup()
                .addGroup(PatientWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientWorkLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientWorkLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnCreateEncounter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PatientWorkLayout.setVerticalGroup(
            PatientWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientWorkLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnCreateEncounter)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        PatientWorkArea.add(PatientWork, "card2");

        AddEncounter.setBackground(new java.awt.Color(228, 241, 254));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("~ Encounter Creation ~");

        lblPatientID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientID.setText("Patient ID:");

        lblPatientFName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientFName.setText("First Name:");

        lblPatientLName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientLName.setText("Last Name:");

        lblPatientAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientAge.setText("Age:");

        lblPatientMobilePhn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientMobilePhn.setText("Mobile Phone:");

        lblPatientListOfDoctors.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientListOfDoctors.setText("List Of Doctors:");

        lblPatientEncounterID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientEncounterID.setText("Encounter ID:");

        lblPatientEncounterTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientEncounterTime.setText("Encounter Time:");

        lblPatientBloodType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientBloodType.setText("Blood Type:");

        lblPatientAdmitDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientAdmitDate.setText("Admit Date:");

        lblPatientSymptoms.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPatientSymptoms.setText("Symptoms:");

        btnSubmitEncounter.setText("Submit Encounter");
        btnSubmitEncounter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitEncounterMouseClicked(evt);
            }
        });

        btnBackToPatientMainPage.setText("<< Back");
        btnBackToPatientMainPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackToPatientMainPageMouseClicked(evt);
            }
        });
        btnBackToPatientMainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToPatientMainPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddEncounterLayout = new javax.swing.GroupLayout(AddEncounter);
        AddEncounter.setLayout(AddEncounterLayout);
        AddEncounterLayout.setHorizontalGroup(
            AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AddEncounterLayout.createSequentialGroup()
                .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEncounterLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddEncounterLayout.createSequentialGroup()
                                .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPatientMobilePhn)
                                    .addComponent(lblPatientAge)
                                    .addComponent(lblPatientLName)
                                    .addComponent(lblPatientFName)
                                    .addComponent(lblPatientID))
                                .addGap(18, 18, 18)
                                .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPatientFName)
                                    .addComponent(txtPatientLName)
                                    .addComponent(txtPatientMobilePhn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(txtPatientID)
                                    .addComponent(txtPatientAge)))
                            .addGroup(AddEncounterLayout.createSequentialGroup()
                                .addComponent(lblPatientListOfDoctors)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatientListOfDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPatientEncounterID)
                            .addComponent(lblPatientEncounterTime)
                            .addComponent(lblPatientBloodType)
                            .addComponent(lblPatientAdmitDate)
                            .addComponent(lblPatientSymptoms))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatientSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPatientAdmitDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(txtPatientBloodType, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPatientEncounterTime, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPatientEncounterID, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(AddEncounterLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btnBackToPatientMainPage))
                    .addGroup(AddEncounterLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnSubmitEncounter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddEncounterLayout.setVerticalGroup(
            AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEncounterLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle1)
                .addGap(38, 38, 38)
                .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEncounterLayout.createSequentialGroup()
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientID)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientFName)
                            .addComponent(txtPatientFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientLName)
                            .addComponent(txtPatientLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientAge)
                            .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientMobilePhn)
                            .addComponent(txtPatientMobilePhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientListOfDoctors)
                            .addComponent(txtPatientListOfDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddEncounterLayout.createSequentialGroup()
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientEncounterID)
                            .addComponent(txtPatientEncounterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientEncounterTime)
                            .addComponent(txtPatientEncounterTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientBloodType)
                            .addComponent(txtPatientBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientAdmitDate)
                            .addComponent(txtPatientAdmitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddEncounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientSymptoms)
                            .addComponent(txtPatientSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnSubmitEncounter)
                .addGap(33, 33, 33)
                .addComponent(btnBackToPatientMainPage)
                .addGap(30, 30, 30))
        );

        PatientWorkArea.add(AddEncounter, "card3");

        PatientWorkSpaceSplitPane.setRightComponent(PatientWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatientWorkSpaceSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PatientWorkSpaceSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientLogOutActionPerformed
        // TODO add your handling code here:
        LoginJFrame lgFrame = new LoginJFrame();
        lgFrame.setVisible(true);
        lgFrame.pack();
        lgFrame.setLocationRelativeTo(null);
        lgFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnPatientLogOutActionPerformed

    private void PatientEncountersjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientEncountersjTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientEncountersjTableMouseClicked

    private void btnCreateEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEncounterActionPerformed
        // TODO add your handling code here:
        PatientWorkArea.removeAll();
        PatientWorkArea.add(AddEncounter);
        PatientWorkArea.repaint();
        PatientWorkArea.revalidate();
    }//GEN-LAST:event_btnCreateEncounterActionPerformed

    private void btnBackToPatientMainPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackToPatientMainPageMouseClicked
        // TODO add your handling code here:
        PatientWorkArea.removeAll();
        PatientWorkArea.add(PatientWork);
        PatientWorkArea.repaint();
        PatientWorkArea.revalidate();
    }//GEN-LAST:event_btnBackToPatientMainPageMouseClicked

    private void btnBackToPatientMainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToPatientMainPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToPatientMainPageActionPerformed

    private void btnSubmitEncounterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitEncounterMouseClicked
        // TODO add your handling code here:
        
        txtPatientFName.setText(personToWorkWith.getfName());
        txtPatientLName.setText(personToWorkWith.getlName());
        txtPatientAge.setText(String.valueOf(personToWorkWith.getAge()));
        txtPatientMobilePhn.setText(String.valueOf(personToWorkWith.getMobilePhn()));
         
    }//GEN-LAST:event_btnSubmitEncounterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientWorkAreaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientWorkAreaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEncounter;
    private javax.swing.JTable PatientEncountersjTable;
    private javax.swing.JPanel PatientToolBar;
    private javax.swing.JPanel PatientWork;
    private javax.swing.JPanel PatientWorkArea;
    private javax.swing.JSplitPane PatientWorkSpaceSplitPane;
    private javax.swing.JButton btnBackToPatientMainPage;
    private javax.swing.JButton btnCreateEncounter;
    private javax.swing.JButton btnPatientLogOut;
    private javax.swing.JButton btnSubmitEncounter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatientAdmitDate;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientBloodType;
    private javax.swing.JLabel lblPatientEncounterID;
    private javax.swing.JLabel lblPatientEncounterTime;
    private javax.swing.JLabel lblPatientFName;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientLName;
    private javax.swing.JLabel lblPatientListOfDoctors;
    private javax.swing.JLabel lblPatientMobilePhn;
    private javax.swing.JLabel lblPatientSymptoms;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTextField txtPatientAdmitDate;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientBloodType;
    private javax.swing.JTextField txtPatientEncounterID;
    private javax.swing.JTextField txtPatientEncounterTime;
    private javax.swing.JTextField txtPatientFName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientLName;
    private javax.swing.JComboBox<String> txtPatientListOfDoctors;
    private javax.swing.JTextField txtPatientMobilePhn;
    private javax.swing.JTextField txtPatientSymptoms;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        //here i am using getModel whose type is TableModel which is used to manipulate our table
        //here we are asking java to convert the ".getModel" whose type is tablemodel to DefaultTableModel using the constructor
        //inside the "()" brackets
        
        DefaultTableModel model = (DefaultTableModel)PatientEncountersjTable.getModel();
        model.setRowCount(0); //deleting the empty records in our JTable
        
        
        
    }
}
